# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professeurs', '0004_professeur_active'),
        ('etudiants', '0006_auto_20180112_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursParticulier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_cours', models.DateTimeField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('eleve_a_paye', models.BooleanField(default=False)),
                ('prof_paye', models.BooleanField(default=False)),
                ('tarif_horaire_eleve', models.CharField(default=30, max_length=200)),
                ('tarif_horaire_prof', models.CharField(default=20, max_length=200)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eleves', models.ManyToManyField(blank=True, null=True, to='etudiants.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('abreviation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='coursparticulier',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursparticuliers.Matiere'),
        ),
        migrations.AddField(
            model_name='coursparticulier',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professeurs.Professeur'),
        ),
    ]
