# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursparticuliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('email_contact', models.EmailField(max_length=254)),
                ('tel_contact', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('regle', 'Cours créé'), ('decline', 'Demande déclinéé')], default='attente', max_length=40)),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursparticulier',
            name='date_demande',
        ),
        migrations.AddField(
            model_name='demandecp',
            name='cours_particulier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursparticuliers.CoursParticulier'),
        ),
        migrations.AddField(
            model_name='demandecp',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursparticuliers.Matiere'),
        ),
        migrations.AddField(
            model_name='demandecp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
