# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursparticuliers', '0002_auto_20180118_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecp',
            name='cours_particulier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursparticuliers.CoursParticulier'),
        ),
        migrations.AlterField(
            model_name='demandecp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
