# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professeurs', '0004_professeur_active'),
        ('ba2', '0003_temoignageeleve'),
        ('etudiants', '0006_auto_20180112_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('periode', models.CharField(blank=True, choices=[('noel', 'Noël'), ('paques', 'Pâques'), ('mai', 'Mai'), ('juillet', 'Juillet/Août')], max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('campus', models.ManyToManyField(to='ba2.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionBlocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('origine', models.CharField(max_length=200, verbose_name='Comment avez-vous entendu parler de Blocus Assistance?')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('suivi_inscription', models.TextField(blank=True)),
                ('code_promo', models.CharField(blank=True, max_length=200, null=True)),
                ('blocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Campus')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.Etudiant')),
            ],
            options={
                'ordering': ['etudiant'],
            },
        ),
        migrations.CreateModel(
            name='ModuleBlocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.CharField(max_length=200)),
                ('sem_or_we', models.CharField(choices=[('sem', 'Semaine'), ('we', 'Weekend'), ('jour', 'Jour')], default='sem', max_length=200)),
                ('blocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('campus', models.ManyToManyField(to='ba2.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(default='08:30')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('absent_justifie', 'Absence justifiée')], default='absent', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.Etudiant')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.InscriptionBlocus')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceJourBlocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesseurBlocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('professeur', 'Professeur'), ('responsable', 'Responsable'), ('nouveau_prof', 'Nouveau Prof')], default='professeur', max_length=50)),
                ('blocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.Professeur')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='jourblocus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.PresenceJourBlocus'),
        ),
        migrations.AddField(
            model_name='inscriptionblocus',
            name='module',
            field=models.ManyToManyField(to='blocus.ModuleBlocus'),
        ),
    ]
