# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ba2', '0001_initial'),
        ('blocus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBlocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.CharField(max_length=200)),
                ('blocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('campus', models.ManyToManyField(blank=True, null=True, to='ba2.Campus')),
            ],
        ),
    ]
