# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='statuts',
            new_name='statut',
        ),
    ]
