# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba2', '0003_temoignageeleve'),
        ('blocus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeurblocus',
            name='campus',
            field=models.ManyToManyField(to='ba2.Campus'),
        ),
    ]
