# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocus', '0002_professeurblocus_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeurblocus',
            name='total',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
