# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0005_etudiant'),
        ('ba2', '0002_auto_20171229_1025'),
        ('blocus', '0003_presencejourblocus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionBlocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('origine', models.CharField(max_length=200, verbose_name='Comment avez-vous entendu parler de Blocus Assistance?')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('suivi_inscription', models.TextField(blank=True)),
                ('code_promo', models.CharField(blank=True, max_length=200, null=True)),
                ('blocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Campus')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.Etudiant')),
                ('module', models.ManyToManyField(to='blocus.ModuleBlocus')),
            ],
            options={
                'ordering': ['etudiant'],
            },
        ),
    ]
