# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocus', '0004_inscriptionblocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleblocus',
            name='sem_or_we',
            field=models.CharField(choices=[('sem', 'Semaine'), ('we', 'Weekend'), ('jour', 'Jour')], default='sem', max_length=200),
        ),
    ]
