# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_auto_20180112_1449'),
        ('blocus', '0005_moduleblocus_sem_or_we'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(default='08:30')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('absent_justifie', 'Absence justifiée')], default='absent', max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.Etudiant')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.InscriptionBlocus')),
                ('jourblocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.PresenceJourBlocus')),
            ],
        ),
    ]
