# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 15:09
from __future__ import unicode_literals

import ba2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('capacite_maximale', models.SmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CampusImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ba2.models.image_upload_to)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Campus')),
            ],
        ),
    ]
