# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba2', '0002_auto_20171229_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemoignageEleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='mes_images/')),
                ('temoignage', models.TextField()),
                ('etude', models.CharField(max_length=200)),
                ('annee', models.CharField(choices=[('BA1', 'BA1'), ('BA2', 'BA2'), ('BA3', 'BA3'), ('MA1', 'MA1'), ('MA2', 'MA2'), ('diplome', 'Diplômé')], max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('categories', models.CharField(choices=[('blocus', 'Blocus Assistés'), ('cours', 'Cours Particuliers'), ('suiviintensif', 'Suivi Intensif')], max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
