# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gsm', models.CharField(max_length=100)),
                ('faculte', models.CharField(max_length=100)),
                ('etudes', models.CharField(max_length=100)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('suivi_prospect', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('non_contacte', 'Pas encore contacté'), ('en_cours', 'En cours/En contact'), ('converti', 'Converti'), ('rate', 'Raté')], default='non_contacte', max_length=40)),
            ],
        ),
    ]
