# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ba2', '0002_auto_20171229_1025'),
        ('professeurs', '0002_auto_20180103_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gsm', models.CharField(max_length=200)),
                ('annee', models.CharField(choices=[('BA1', 'BA1'), ('BA2', 'BA2'), ('BA3', 'BA3'), ('MA1', 'MA1'), ('MA2', 'MA2'), ('diplome', 'Diplômé')], max_length=200)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, upload_to='mes_images/')),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Etude')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Faculte')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ba2.Universite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
