# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocus', '0002_professeurblocus_campus'),
        ('professeurs', '0004_professeur_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneeBlocusProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('remarque', models.TextField()),
                ('blocus', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blocus.Blocus')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.Professeur')),
            ],
        ),
    ]
