# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0005_journeeblocusprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeeblocusprof',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
