# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0006_auto_20180212_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeeblocusprof',
            name='total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
