# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0007_journeeblocusprof_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeeblocusprof',
            name='date',
            field=models.DateField(),
        ),
    ]
