# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ba2', '0003_temoignageeleve'),
        ('professeurs', '0008_auto_20180212_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeeblocusprof',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ba2.Campus'),
        ),
    ]
