# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_auto_20180112_1449'),
        ('blocus', '0003_professeurblocus_total'),
        ('professeurs', '0009_journeeblocusprof_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportBlocusJournalier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.TextField()),
                ('objectif_atteint', models.BooleanField(default=False)),
                ('bilan', models.TextField()),
                ('date', models.DateField()),
                ('recommandation', models.TextField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('concentration', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=100)),
                ('productivité', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=100)),
                ('moral', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rapport_envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.Professeur')),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.Presence')),
            ],
        ),
        migrations.CreateModel(
            name='RapportBlocusModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('rapport_envoye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.Professeur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.Etudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocus.ModuleBlocus')),
            ],
        ),
        migrations.AddField(
            model_name='rapportblocusjournalier',
            name='rapportmodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.RapportBlocusModule'),
        ),
    ]
