# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0011_auto_20180213_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportblocusjournalier',
            name='bilan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportblocusjournalier',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportblocusjournalier',
            name='presence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blocus.Presence'),
        ),
        migrations.AlterField(
            model_name='rapportblocusjournalier',
            name='recommandation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
