# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0012_auto_20180213_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportblocusjournalier',
            name='statut',
            field=models.CharField(choices=[('objectif_fixe', 'Objectif Fixé'), ('bilan_realise', 'Bilan Réalisé'), ('rapport_envoye', 'Rapport Envoyé')], default='objectif_fixe', max_length=100),
        ),
    ]
