# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0013_rapportblocusjournalier_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapportblocusjournalier',
            old_name='concentration',
            new_name='proactivite',
        ),
    ]
