# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='extended_user',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='etude',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='faculte',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='universite',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
