# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0005_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
